# -*- coding: utf-8 -*-
"""capstoneProject_NEWS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d3xV8jk_WRUkVtsBL_8i5LKBo-ojwlzv

### Mount Google Drive
First, we need to mount Google Drive to access the CSV files.
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Imports and Data Loading
Import necessary libraries, define helper functions, and load the dataset into a pandas DataFrame.
"""

import re
from pathlib import Path
from collections import Counter

import numpy as np
import pandas as pd
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.feature_extraction import text as sklearn_text
import matplotlib.pyplot as plt
import seaborn as sns # Added for enhanced plotting
import os

# Base path to data CSV files in Google Drive
base_path = '/content/drive/MyDrive/ColabNotebooks/CapstoneProject/dataset/'

CSV_FILES = [
    'business_data.csv',
    'education_data.csv',
    'entertainment_data.csv',
    'sports_data.csv',
    'technology_data.csv',
]

def print_section(title):
    print('\n' + '=' * 80)
    print(title)
    print('=' * 80 + '\n')

def load_data(files):
    frames = []
    for path in files:
        df = pd.read_csv(base_path+path)
        df['source_file'] = path
        frames.append(df)
    return pd.concat(frames, ignore_index=True)

df = load_data(CSV_FILES)

"""## 1. Data Report
- Understanding the data
- Check the number of rows and columns in each dataset
- Assess the completeness and structure of the columns (headlines, description, content, URL, category)
- Ensure clarity on what each column represents
- Rename variables if necessary for improved readability
"""

def data_report(df_to_report):
    print_section('Data Report')
    print('Total rows:', len(df_to_report))
    print('Total columns:', len(df_to_report.columns))
    print('Columns:', df_to_report.columns.tolist())
    print('\nColumn types:')
    print(df_to_report.dtypes)
    print('\nMissing values by column:')
    print(df_to_report.isna().sum())

    # Exclude columns with list dtypes from duplicated check
    # Assuming 'tokens' is the only column that contains lists and causes issues
    # If there are other list columns, they should also be excluded
    df_for_duplicate_check = df_to_report.drop(columns=['tokens'], errors='ignore')
    print('\nNumber of duplicate rows (excluding list columns):', df_for_duplicate_check.duplicated().sum())

    print('\nCategory distribution:')
    print(df_to_report['category'].value_counts())
    print('\nSample rows:')
    display(df_to_report.head(3))

data_report(df)

"""## 2. Initial Exploratory Data Analysis
- Analyze word counts or character lengths for the headlines, description, and content
- Determine the distribution of articles in each category (e.g., Sports, Technology)
- Create word clouds or frequency plots to show the most common words used in each category
- Investigate the length of headlines, description, and content across different categories to spot patterns (e.g., longer articles in one category)
"""

print_section('Initial Exploratory Data Analysis')

print('Headline length stats:')
print(df['headline_word_count'].describe())
print('\nDescription length stats:')
print(df['description_word_count'].describe())
print('\nContent length stats:')
print(df['content_word_count'].describe())

def plot_category_distribution(df_to_plot):
    counts = df_to_plot['category'].value_counts().sort_values(ascending=False)
    fig, ax = plt.subplots(figsize=(8, 5))
    counts.plot(kind='bar', color='tab:blue', ax=ax)
    ax.set_title('Article Count by Category')
    ax.set_xlabel('Category')
    ax.set_ylabel('Count')
    plt.tight_layout()
    plt.show()
    plt.close(fig)

plot_category_distribution(df)

def plot_length_distributions(df_to_plot):
    fig, axes = plt.subplots(3, 1, figsize=(10, 12), constrained_layout=True)
    df_to_plot.boxplot(column=['headline_word_count'], by='category', ax=axes[0], grid=False)
    axes[0].set_title('Headline Word Count by Category')
    axes[0].set_xlabel('Category')
    axes[0].set_ylabel('Headline Word Count')
    df_to_plot.boxplot(column=['description_word_count'], by='category', ax=axes[1], grid=False)
    axes[1].set_title('Description Word Count by Category')
    axes[1].set_xlabel('Category')
    axes[1].set_ylabel('Description Word Count')
    df_to_plot.boxplot(column=['content_word_count'], by='category', ax=axes[2], grid=False)
    axes[2].set_title('Content Word Count by Category')
    axes[2].set_xlabel('Category')
    axes[2].set_ylabel('Content Word Count')
    fig.suptitle('Length Distribution Across Categories', fontsize=16)
    plt.tight_layout()
    plt.show()
    plt.close(fig)

plot_length_distributions(df)

"""## 3. Data Pre-processing
- Remove stopwords (common words like "and," "the" which don’t contribute to meaning)
- Handle punctuation, special characters, numbers, and other non-alphabetic symbols
- Perform case normalization (convert text to lowercase)
- Handle missing values in the description or content fields. This could include dropping rows or filling missing values with a placeholder
- Identify and handle articles with unusually short or long content (e.g., less than 5 words could be an outlier)
- Transform text data into numerical format using vectorization techniques (e.g., TF-IDF, Bag of Words, or word embeddings)

### Select VECTORIZATION_METHOD
#### options: 'bow', 'tfidf', 'embeddings'
"""

VECTORIZATION_METHOD = 'embeddings'  # options: 'bow', 'tfidf', 'embeddings'

STOP_WORDS = sklearn_text.ENGLISH_STOP_WORDS
DROP_OUTLIERS = True
MIN_CONTENT_WORDS = 5
MAX_CONTENT_WORDS = 5000
MAX_FEATURES = 10000
EMBEDDING_SIZE = 100

def normalize_text(text, remove_stopwords=True):
    if pd.isna(text):
        return ''
    text = str(text)
    text = re.sub(r'http\S+|www\S+', ' ', text)
    text = re.sub(r'<[^>]+>', ' ', text)
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    text = text.lower()
    tokens = text.split()
    if remove_stopwords:
        tokens = [token for token in tokens if token not in STOP_WORDS and len(token) > 1]
    else:
        tokens = [token for token in tokens if len(token) > 1]
    return ' '.join(tokens)

def compute_length_features(df_to_process):
    df_to_process['headline_length'] = df_to_process['headlines'].fillna('').astype(str).apply(len)
    df_to_process['headline_word_count'] = df_to_process['headlines'].fillna('').astype(str).apply(lambda s: len(s.split()))
    df_to_process['description_length'] = df_to_process['description'].fillna('').astype(str).apply(len)
    df_to_process['description_word_count'] = df_to_process['description'].fillna('').astype(str).apply(lambda s: len(s.split()))
    df_to_process['content_length'] = df_to_process['content'].fillna('').astype(str).apply(len)
    df_to_process['content_word_count'] = df_to_process['content'].fillna('').astype(str).apply(lambda s: len(s.split()))
    return df_to_process

def preprocess_dataframe(df_to_process):
    df_to_process = df_to_process.copy()
    for column in ['headlines', 'description', 'content']:
        df_to_process[column] = df_to_process[column].fillna('').astype(str)
    df_to_process['category'] = df_to_process['category'].astype(str).str.strip().str.lower()

    df_to_process = compute_length_features(df_to_process)
    df_to_process['is_short_content'] = df_to_process['content_word_count'] < MIN_CONTENT_WORDS
    df_to_process['is_long_content'] = df_to_process['content_word_count'] > MAX_CONTENT_WORDS
    df_to_process['content_outlier'] = df_to_process['is_short_content'] | df_to_process['is_long_content']

    if DROP_OUTLIERS:
        before = len(df_to_process)
        df_to_process = df_to_process[~df_to_process['content_outlier']].copy()
        print(f'Dropped {before - len(df_to_process)} outlier rows based on content length.')

    df_to_process['headlines_clean'] = df_to_process['headlines'].apply(lambda x: normalize_text(x, remove_stopwords=True))
    df_to_process['description_clean'] = df_to_process['description'].apply(lambda x: normalize_text(x, remove_stopwords=True))
    df_to_process['content_clean'] = df_to_process['content'].apply(lambda x: normalize_text(x, remove_stopwords=True))
    df_to_process['text'] = (
        df_to_process['headlines_clean'] + ' ' +
        df_to_process['description_clean'] + ' ' +
        df_to_process['content_clean']
    ).str.strip()
    df_to_process['tokens'] = df_to_process['text'].apply(lambda x: x.split())
    return df_to_process # Corrected: return df_to_process instead of df

def build_vectorizer(df_to_vectorize):
    if VECTORIZATION_METHOD == 'bow':
        vectorizer = CountVectorizer(
            strip_accents='unicode',
            stop_words='english',
            max_features=MAX_FEATURES,
            ngram_range=(1, 2),
        )
        X = vectorizer.fit_transform(df_to_vectorize['text'])
        print('BoW matrix shape:', X.shape)
        print('Sample BoW feature names:', vectorizer.get_feature_names_out()[:20])
        return X, vectorizer

    if VECTORIZATION_METHOD == 'tfidf':
        vectorizer = TfidfVectorizer(
            strip_accents='unicode',
            stop_words='english',
            max_features=MAX_FEATURES,
            ngram_range=(1, 2),
        )
        X = vectorizer.fit_transform(df_to_vectorize['text'])
        print('TF-IDF matrix shape:', X.shape)
        print('Sample TF-IDF feature names:', vectorizer.get_feature_names_out()[:20])
        return X, vectorizer

    if VECTORIZATION_METHOD == 'embeddings':
        embedding_vectorizer = TfidfVectorizer(
            strip_accents='unicode',
            stop_words='english',
            max_features=MAX_FEATURES,
            ngram_range=(1, 2),
        )
        X_sparse = embedding_vectorizer.fit_transform(df_to_vectorize['text'])
        n_components = min(EMBEDDING_SIZE, X_sparse.shape[1] - 1)
        svd = TruncatedSVD(n_components=n_components, random_state=42)
        X = svd.fit_transform(X_sparse)
        print('Embedding matrix shape:', X.shape)
        np.save('article_embeddings.npy', X)
        return X, {'vectorizer': embedding_vectorizer, 'svd': svd}

    raise ValueError(f'Unsupported vectorization method: {VECTORIZATION_METHOD}')

# --- Execution of Data Pre-processing steps ---
print_section('Data Pre-processing Execution')

df = preprocess_dataframe(df) # Update the global df with preprocessed data

print('Cleaned text sample:')
display(df[['headlines_clean', 'description_clean', 'content_clean', 'text']].head(2).to_dict(orient='records'))

merged_out = 'merged_preprocessed_data.csv'
df.to_csv(merged_out, index=False)
print('Saved merged preprocessed dataset to', merged_out)

print('Using vectorization method:', VECTORIZATION_METHOD)
X, vectorizer = build_vectorizer(df)
print_section('Text Vectorization Completed')

"""## 4. Final Exploratory Data Analysis
- Word clouds for each category
- Bar plots or histograms showing the frequency of articles in each category
- Distribution of article lengths (word count) across different categories
"""

import matplotlib.pyplot as plt
from collections import Counter
import pandas as pd
import seaborn as sns
from wordcloud import WordCloud # Import WordCloud

def tokenize_and_filter(text):
    return [token for token in normalize_text(text).split() if token not in STOP_WORDS and len(token) > 1]

def top_n_words(series, n=25):
    counts = Counter()
    for value in series:
        tokens = tokenize_and_filter(value)
        counts.update(tokens)
    return counts.most_common(n)

def plot_top_words_by_category(df_to_plot, n=15):
    categories = df_to_plot['category'].unique()
    n_cols = 2 # Number of columns for subplots
    n_rows = (len(categories) + n_cols - 1) // n_cols # Calculate rows needed

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(15, 6 * n_rows), constrained_layout=True)
    axes = axes.flatten() # Flatten in case of single row/column

    for i, category in enumerate(categories):
        subset = df_to_plot[df_to_plot['category'] == category]
        top_words_list = top_n_words(subset['content_clean'], n=n)
        words, counts = zip(*top_words_list)

        sns.barplot(x=list(counts), y=list(words), ax=axes[i], palette='viridis', hue=list(words), legend=False)
        axes[i].set_title(f'Top {n} words in {category} articles')
        axes[i].set_xlabel('Count')
        axes[i].set_ylabel('Word')

    # Hide any unused subplots
    for j in range(i + 1, len(axes)):
        fig.delaxes(axes[j])

    fig.suptitle('Most Common Words by Category', fontsize=18, y=1.02)
    plt.show()
    plt.close(fig)

def generate_word_clouds(df_to_plot):
    print_section('Generating Word Clouds')
    categories = df_to_plot['category'].unique()
    for category in categories:
        subset_text = " ".join(df_to_plot[df_to_plot['category'] == category]['content_clean'])
        if subset_text:
            wordcloud = WordCloud(width=800, height=400, background_color='white').generate(subset_text)
            plt.figure(figsize=(10, 5))
            plt.imshow(wordcloud, interpolation='bilinear')
            plt.axis('off')
            plt.title(f'Word Cloud for {category.capitalize()} Articles')
            plt.show()
            plt.close()
        else:
            print(f"No clean content found for category: {category}")


print_section('Final Exploratory Data Analysis Execution')

generate_word_clouds(df) # Call the word cloud function

# Adding required plots for Final EDA
plot_category_distribution(df)

plot_length_distributions(df)

plot_top_words_by_category(df, n=15)

# Top words analysis (text table)
all_top_words = {}
for category, subset in df.groupby('category'):
    top_words = top_n_words(subset['content_clean'])
    formatted_words = [f'{word}: {count}' for word, count in top_words]
    all_top_words[category] = formatted_words

top_words_df = pd.DataFrame(all_top_words)

print('\n### Top words in content by Category\n')
print(top_words_df.to_markdown(index=False))

print_section('Milestone 1 Completed')